spring:
  jedis:
    database: 0
    host: 101.132.191.77
    port: 6379
    password: 123456
    pool:
      min-idle: 0 # 连接池中的最小空闲连接
        max-active: 8 # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1 # 连接池中的最大空闲连接